apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: university-chatbot
spec:
  selector:
    app: auth-service
  ports:
    - port: 5003
      targetPort: 5003
  type: ClusterIP
